- hosts: certificate
  vars:
    certbot_auto_renew_user: root
    certbot_auto_renew_hour: "5"
    certbot_auto_renew_minute: "20"
    certbot_create_if_missing: yes
    certbot_create_method: standalone
    certbot_admin_email: '{{ admin_email }}'
    # За да добавиш домейн, сложи го на първо място в списъка domains
    certbot_certs:
      - domains:
          - '{{ nextcloud_domain }}'
    certbot_create_standalone_stop_services:
      - nginx

    # Add expand flag
    certbot_create_command: >-
      {{ certbot_script }} certonly --expand --standalone --noninteractive --agree-tos --email {{ cert_item.email | default(certbot_admin_email) }} -d {{ cert_item.domains | join(',') }}

  roles:
    - role: geerlingguy.certbot
      become: yes

  tasks:
    - name: create certbot webroot
      become: yes
      file:
        name: '{{ certbot_webroot }}'
