- name: install requirements
  become: yes
  apt:
    name:
      - php7.4-pgsql
      - php-fpm
      - php7.4-zip
      - php7.4-dom
      - php7.4-xml
      - php7.4-mbstring
      - php7.4-gd
      - php7.4-curl
      - php7.4-gmp
      - php7.4-bcmath
      - php7.4-intl
      - php-imagick
      - redis-server
      - php-redis

- name: check whether Nextcloud is installed
  stat:
    path: '{{ nextcloud_root }}'
  register: nextcloud_root_stat

- name: install Nextcloud
  when: not nextcloud_root_stat.stat.exists
  block:
    - name: fetch Nextcloud
      get_url:
        url: https://download.nextcloud.com/server/releases/nextcloud-20.0.1.tar.bz2
        dest: /tmp/nextcloud.tar.bz2

    - name: unarchive Nextcloud
      unarchive:
        src: /tmp/nextcloud.tar.bz2
        remote_src: yes
        dest: /tmp/

    - name: put Nextcloud in place
      become: yes
      copy:
        src: /tmp/nextcloud
        remote_src: yes
        dest: '/opt'
        mode: '0740'
        owner: 'www-data'
        group: 'www-data'

- name: create database
  become: yes
  become_user: postgres
  postgresql_db: name={{nextcloud_db_name}}

- name: make database user have access to the database
  become: yes
  become_user: postgres
  postgresql_user: db={{nextcloud_db_name}} name={{nextcloud_db_user}} password={{nextcloud_db_password}} priv=ALL

- name: put Nextcloud config in place
  become: yes
  become_user: www-data
  template:
    src: 'files/config.php'
    dest: '{{ nextcloud_root }}/config/'
