<?php
$CONFIG = array (
  'instanceid' => '{{ nextcloud_instance_id }}',
  'passwordsalt' => '{{ nextcloud_password_salt }}',
  'secret' => '{{ nextcloud_secret }}',
  'trusted_domains' =>
  array (
    0 => '{{ nextcloud_domain }}',
  ),
  'datadirectory' => '{{ nextcloud_root }}/data',
  'dbtype' => 'pgsql',
  'version' => '20.0.1.1',
  'overwrite.cli.url' => 'https://{{ nextcloud_domain }}',
  'dbname' => '{{ nextcloud_db_name }}',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '{{ nextcloud_db_user }}',
  'dbpassword' => '{{ nextcloud_db_password }}',
  'installed' => true,
  "force_language" => "bg",
  'memcache.local' => '\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => array(
    'host' => 'localhost',
    'port' => 6379,
  ),
  'skeleton' => '', # no default files
  'maintenance' => false,
  'mail_from_address' => 'oblak',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'smtp.eu.mailgun.org',
  'mail_smtpport' => '465',
  'mail_domain' => '{{ mail_domain}}',
  'mail_smtpname' => 'postmaster@{{ mail_domain }}',
  'mail_smtppassword' => '{{ mail_smtppassword }}',
  'mail_smtpsecure' => 'ssl',
  'oidc_login_client_id' => 'nextcloud',
  'oidc_login_client_secret' => '{{ oidc_login_client_secret }}',
  'oidc_login_provider_url' => 'https://az.zhiva.be/auth/realms/zhiva-mrezha',
  'oidc_login_logout_url' => 'https://az.zhiva.be/auth/realms/zhiva-mrezha/protocol/openid-connect/logout?redirect_uri=https%3A%2F%2Foblak.otselo.eu%2F',
  'oidc_login_auto_redirect' => true,
  'oidc_login_redir_fallback' => true,
  'oidc_login_disable_registration' => false,
  'oidc_login_attributes' => array(
   'id' => 'preferred_username',
   'mail' => 'email',
  ),
  // If you are running Nextcloud behind a reverse proxy, make sure this is set
  'overwriteprotocol' => 'https',
);
